steps:   
- task: ManualValidation@0
    timeoutInMinutes: 1440 # task times out in 1 day
    inputs:
        notifyUsers: |
          chunyu@microsoft.com
          yuchun_green@hotmail.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'