steps:
- template: VariableSetTask.yml
- script: |
    npm install -g publish-sdkcodgen-pipeline-result
    echo $pwd
    mkdir generated
    az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
    az storage blob download -c depthcoverage -f $(CodeGenerationName)-$(Build.BuildId)-generated.tar.gz -n $(CodeGenerationName)-$(Build.BuildId)-generated.tar.gz --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
    tar -xzvf $(CodeGenerationName)-$(Build.BuildId)-generated.tar.gz -C generated/
    ls -l generated/
  displayName: 'Before $(TASK_KEY)'
  # env: { 
  #   'PIPELINE_TOKEN': "$(PIPELINE_TOKEN)"
  # }