steps:
- task: GoTool@0
  inputs:
    version: '1.16.x'
    goPath: '/home/vsts/work/1/s/go'
    goBin: '/home/vsts/work/1/s/go/bin'
- bash: |
    ls -l
    pwd
    mkdir -p ./go/src/github.com/terraform-providers
    echo "https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com" > ~/.git-credentials
    git clone --branch depth-$(TARGET)-$(ResourceProvider) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com/$(Swagger_ORG)/azure-rest-api-specs.git
    cd ./go/src/github.com/terraform-providers
    git clone --branch depth-$(TARGET)-$(ResourceProvider) https://$(PIPELINE_USER):$(PIPELINE_TOKEN)@github.com/$(TF_ORG)/terraform-provider-azurerm.git
    cd terraform-provider-azurerm
    export GOPATH=/home/vsts/work/1/s/go
    echo $GOPATH
    GO111MODULE=off go get github.com/shopspring/decimal
    make tools
  displayName: 'Setup TF Test env'