steps:
# - task: DownloadPipelineArtifact@2
#   inputs:
#     buildType: 'current'
#     artifactName: 'variables'
#     targetPath: '$(Pipeline.Workspace)'
# - task: DownloadPipelineArtifact@2
#   inputs:
#     buildType: 'current'
#     artifactName: 'sdkvariables'
#     targetPath: '$(Pipeline.Workspace)/sdk'
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    patterns: '*variables/**'
    targetPath: '$(Pipeline.Workspace)'
# - download: current
  
# - download: current
#   patterns: 'sdkvariables/**'
- script: |
    set -x
    ls -l $(Pipeline.Workspace)
    ls -l $(Pipeline.Workspace)/variables/
    ls -l $(Pipeline.Workspace)/sdkvariables/
    ls -l $(Pipeline.Workspace)/variables/variables
    ls -l $(Pipeline.Workspace)/sdkvariables/sdkvariables
    ResourceProvider=$(cat $(Pipeline.Workspace)/variables/variables/ResourceProvider)
    echo "##vso[task.setvariable variable=ResourceProvider]$ResourceProvider"
        
    README_FILE=$(cat $(Pipeline.Workspace)/variables/variables/README_FILE)
    echo "##vso[task.setvariable variable=README_FILE]$README_FILE"

    target=$(cat $(Pipeline.Workspace)/variables/variables/TARGET)
    echo "##vso[task.setvariable variable=TARGET]$target"

    tag=$(cat $(Pipeline.Workspace)/variables/variables/TAG)
    echo "##vso[task.setvariable variable=TAG]$tag"

    resources=$(cat $(Pipeline.Workspace)/variables/variables/RESOURCES)
    echo "##vso[task.setvariable variable=RESOURCES]$resources"

    af=$(cat $(Pipeline.Workspace)/variables/variables/Artifact)
    if [ -f "$(Pipeline.Workspace)/sdkvariables/sdkvariables/Artifact" ]; then
      af=$(cat $(Pipeline.Workspace)/sdkvariables/sdkvariables/Artifact)
    fi
    echo "##vso[task.setvariable variable=Artifact]$af"

    package=$(cat $(Pipeline.Workspace)/variables/variables/Package)
    if [ -f "$(Pipeline.Workspace)/sdkvariables/sdkvariables/Package" ]; then
      package=$(cat $(Pipeline.Workspace)/sdkvariables/sdkvariables/Package)
    fi
    echo "##vso[task.setvariable variable=Package]$package"

    echo $ResourceProvider
    echo $target
    echo $tag
    echo $af
    echo $package
    echo 'end' 
  displayName: 'set variable'
  condition: always()