steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'variables'
    targetPath: '$(Pipeline.Workspace)'
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'sdkvariables'
    targetPath: '$(Pipeline.Workspace)/sdk'
- script: |
    ls -l
    ResourceProvider=$(cat $(Pipeline.Workspace)/variables/ResourceProvider)
    echo "##vso[task.setvariable variable=ResourceProvider]$ResourceProvider"
        
    README_FILE=$(cat $(Pipeline.Workspace)/variables/README_FILE)
    echo "##vso[task.setvariable variable=README_FILE]$README_FILE"

    target=$(cat $(Pipeline.Workspace)/variables/TARGET)
    echo "##vso[task.setvariable variable=TARGET]$target"

    tag=$(cat $(Pipeline.Workspace)/variables/TAG)
    echo "##vso[task.setvariable variable=TAG]$tag"

    resources=$(cat $(Pipeline.Workspace)/variables/RESOURCES)
    echo "##vso[task.setvariable variable=RESOURCES]$resources"

    af=$(cat $(Pipeline.Workspace)/variables/Artifact)
    if [ -f "$(Pipeline.Workspace)/sdk/sdkvariables/Artifact" ]; then
      af=$(cat $(Pipeline.Workspace)/sdk/sdkvariables/Artifact)
    fi
    echo "##vso[task.setvariable variable=Artifact]$af"

    package=$(cat $(Pipeline.Workspace)/variables/Package)
    if [ -f "$(Pipeline.Workspace)/sdk/sdkvariables/Package" ]; then
      package=$(cat $(Pipeline.Workspace)/sdk/sdkvariables/Package)
    fi
    echo "##vso[task.setvariable variable=Package]$package"

    echo $ResourceProvider
    echo $target
    echo $tag
    echo $af
    echo $package
    echo 'end' 
  displayName: 'set variable'